import tempfile
from pathlib import Path

from canonical.runtime import global_retrieval_entrypoint_v4 as e
from canonical.runtime import retrieval_live_event_ledger_v1 as ledger

ROOT=Path(__file__).resolve().parents[2]

# Canonical search action executes and is measured.
with tempfile.TemporaryDirectory() as td:
    event_path=Path(td)/"events.jsonl"
    calls={"n":0}
    def web_provider(action):
        calls["n"]+=1
        return {"status":"SUCCESS","candidates":[{"url":"https://example.test/result"}],"request_count":1}

    action={"action":"QUERY_SOURCE","action_id":"WEB-Q1","source_id":"GENERAL_OPEN_WEB","query":"test capability"}
    out=e.execute_authorized_action(
        root=ROOT,episode_id="EP-WEB",sequence=1,action=action,
        provider=web_provider,source_epoch="E-WEB",event_path=event_path,
    )
    assert out["status"]=="PASS__AUTHORIZED_LIVE_RETRIEVAL_ACTION_EXECUTED_AND_MEASURED",out
    assert calls["n"]==1
    assert out["event_appended"] is True
    ev=ledger.load_jsonl(event_path)
    assert len(ev)==1
    assert ev[0]["source_id"]=="GENERAL_OPEN_WEB"
    assert ev[0]["latency_seconds"]>0

# Exact queryless enumeration action is generated by the source-bound planner,
# then accepted by the same entrypoint for execution.
with tempfile.TemporaryDirectory() as td:
    event_path=Path(td)/"events.jsonl"
    plan=e.compile_authorized_plan(
        root=ROOT,query_actions=[],source_epoch="E-PYPI",
        include_source_ids=["PYPI_PUBLIC_PROJECTS"],
    )
    assert plan["status"].startswith("PASS__"),plan
    actions=plan["plan"]["actions"]
    enums=[x for x in actions if x["action"]=="ENUMERATE_BOUNDED_SOURCE"]
    assert len(enums)==1
    enum_action=enums[0]
    assert enum_action["scope_id"]=="PYPI_PUBLIC_PROJECT_NAMES@E-PYPI"

    calls={"n":0}
    def enum_provider(action):
        calls["n"]+=1
        assert action["action_id"]==enum_action["action_id"]
        assert action["scope_id"]=="PYPI_PUBLIC_PROJECT_NAMES@E-PYPI"
        return {"status":"SUCCESS","candidates":[{"package":"example-package"}],"request_count":1}

    out=e.execute_authorized_action(
        root=ROOT,episode_id="EP-PYPI",sequence=1,action=enum_action,
        provider=enum_provider,source_epoch="E-PYPI",event_path=event_path,
    )
    assert out["status"]=="PASS__AUTHORIZED_LIVE_RETRIEVAL_ACTION_EXECUTED_AND_MEASURED",out
    assert calls["n"]==1
    assert ledger.load_jsonl(event_path)[0]["source_id"]=="PYPI_PUBLIC_PROJECTS"

# Invented source fails before provider call.
with tempfile.TemporaryDirectory() as td:
    event_path=Path(td)/"events.jsonl"
    calls={"n":0}
    def should_not_run(action):
        calls["n"]+=1
        raise AssertionError("provider should not execute")
    bad=e.execute_authorized_action(
        root=ROOT,episode_id="EP-BAD",sequence=1,
        action={"action":"QUERY_SOURCE","action_id":"BAD","source_id":"INVENTED_MAGIC_SEARCH","query":"x"},
        provider=should_not_run,source_epoch="E-BAD",event_path=event_path,
    )
    assert bad["status"]=="FAIL_CLOSED__AUTHORIZED_PLAN_UNAVAILABLE"
    assert calls["n"]==0
    assert not event_path.exists()

print("test_global_retrieval_entrypoint_v4: PASS")
