"""Universal zero-reality proof for Unknown-Domain V6.

V6 composes three independently necessary repairs without weakening the original
accepted-input quantifier:
1. Candidate V3 restores exact ADD2 IEEE-754 role order.
2. Generator V4 makes semantically distinct evaluator-visible IDs structural,
   so truncated-token collisions cannot collapse a case.
3. Generator V5 is total on the exact built-in str/bytes domain emitted by the
   frozen one-use production launcher and rejects spoofed or subclass-widened
   Python objects before legacy strict-UTF8 HMAC/randomness helpers.

No production or terminal case is generated by this proof.
"""
from __future__ import annotations

import hashlib
from fractions import Fraction
from pathlib import Path
from typing import Any

from canonical.runtime import unknown_domain_direct_candidate_v1 as c1
from canonical.runtime import unknown_domain_direct_candidate_v2 as c2
from canonical.runtime import unknown_domain_direct_candidate_v3 as c3
from canonical.runtime import unknown_domain_direct_hidden_generator_v1 as g1
from canonical.runtime import unknown_domain_direct_hidden_generator_v2 as g2
from canonical.runtime import unknown_domain_direct_hidden_generator_v4 as g4
from canonical.runtime import unknown_domain_direct_hidden_generator_v5 as g5
from canonical.runtime import unknown_domain_direct_hidden_scorer_v1 as scorer
from canonical.runtime import unknown_domain_direct_execution_harness_v1 as harness

SCHEMA="PROJECT_BRAIN_UNKNOWN_DOMAIN_DIRECT_V6_UNIVERSAL_PROOF_V1"

EXPECTED_BLOBS={
 "canonical/runtime/unknown_domain_direct_candidate_v1.py":"a2a77269a8175ce315b466035049da0f761b8734",
 "canonical/runtime/unknown_domain_direct_candidate_v2.py":"4470716f95a559a700e461262df909ae19a41651",
 "canonical/runtime/unknown_domain_direct_candidate_v3.py":"8df7f13455b710623806a8219174b397a2c3c442",
 "canonical/runtime/unknown_domain_direct_hidden_generator_v1.py":"f974a4594c78e74693c7ba5a19f131dfa481b937",
 "canonical/runtime/unknown_domain_direct_hidden_generator_v2.py":"d077028c9bde534dc4bc6eb0d1f776341f9d59f8",
 "canonical/runtime/unknown_domain_direct_hidden_generator_v4.py":"e52858b9fef2d795f72b45cd3ae82ad04344aa91",
 "canonical/runtime/unknown_domain_direct_hidden_generator_v5.py":"0faa62fce4bc2f2a99c173b0a10a32d5e1c6a244",
 "canonical/runtime/unknown_domain_direct_hidden_scorer_v1.py":"e8cf5d1b5d311644725a751c15e6235958fb587d",
 "canonical/runtime/unknown_domain_direct_execution_harness_v1.py":"04fe06f4eed081c4cb6197b12f2d92bd396aeafd",
 "canonical/tests/test_unknown_domain_direct_v5.py":"1961cff0013ff9f17feca981409d89d01ecf6769",
}

PRODUCTION_DOMAIN_BINDING={
 "repository":"moxnixmdj/verification-capsule-runner",
 "launcher_commit":"50fe4f4a8bbfcf4fc465e3dba94fd9886e46072e",
 "launcher_path":"canonical/runtime/unknown_domain_direct_production_once_v1.py",
 "launcher_git_blob_sha":"7f05674904a4b3223cb26993a1e2e4b0bac8a0e7",
 "workflow_commit":"0839401ecfc4ba7ae87bfb85609f29665efa1ea3",
 "workflow_path":".github/workflows/unknown-domain-direct-one-use-production.yml",
 "workflow_git_blob_sha":"990b4fe712ca509f3e01c8e632c75416a3cd0b98",
 "beacon_constructor":"beacon = \"UDIR-PROD-\" + secrets.token_hex(24)",
 "secret_constructor":"evaluator_secret = secrets.token_bytes(32)",
 "reachable_types":{"beacon":"EXACT_BUILTIN_STR","evaluator_secret":"EXACT_BUILTIN_BYTES"},
}


def _git_blob_sha(path:Path)->str:
    data=path.read_bytes()
    return hashlib.sha1(b"blob "+str(len(data)).encode()+b"\0"+data).hexdigest()


def _root()->Path:
    return Path(__file__).resolve().parents[2]


def _verify_bindings(root:Path)->dict[str,str]:
    got={rel:_git_blob_sha(root/rel) for rel in EXPECTED_BLOBS}
    bad={rel:{"expected":EXPECTED_BLOBS[rel],"got":got[rel]}
         for rel in EXPECTED_BLOBS if got[rel]!=EXPECTED_BLOBS[rel]}
    if bad:
        raise AssertionError("EXACT_SUBJECT_BLOB_MISMATCH:"+repr(bad))
    return got


def _string_totality()->dict[str,Any]:
    assert g5.BEACON_CANONICALIZATION=="UTF8_SURROGATEPASS_BYTES_TO_LOWER_HEX_WITH_V5_PREFIX"
    assert g5.SECRET_CANONICALIZATION=="UTF8_SURROGATEPASS_FOR_STR__BYTES_IDENTITY"
    assert g5.STRING_DOMAIN_TOTALITY=="TOTAL_FOR_FROZEN_PRODUCTION_LAUNCHER_EXACT_BUILTIN_STR_BYTES_DOMAIN"

    # The frozen one-use production launcher constructs beacon using built-in
    # string concatenation over secrets.token_hex() and evaluator_secret using
    # secrets.token_bytes(32). The reachable production domain is therefore
    # exact built-in str x exact built-in bytes, not Python's spoofable
    # isinstance relation.
    production_beacon="UDIR-PROD-"+"a"*48
    production_secret=b"S"*32
    assert type(production_beacon) is str
    assert type(production_secret) is bytes
    assert g5._canonical_beacon(production_beacon).isascii()
    assert g5._secret_bytes_total(production_secret)==production_secret

    # UTF-8+surrogatepass remains total and injective for every finite exact
    # built-in str admitted by the nonproduction string path.
    seen=set()
    for cp in range(0xD800,0xE000):
        value="A"*16+chr(cp)
        assert type(value) is str
        out=g5._canonical_beacon(value)
        assert out.isascii()
        seen.add(out)
    assert len(seen)==0x800
    normal={g5._canonical_beacon(x) for x in (
        "A"*16+"�",
        "A"*16+"😀",
        "Ω"*16,
        "\x00"+"C"*16,
    )}
    assert not (seen & normal)

    class SpoofStr:
        @property
        def __class__(self):
            return str
    class SpoofBytes:
        @property
        def __class__(self):
            return bytes
    class RealStrSubclass(str):
        pass
    class RealBytesSubclass(bytes):
        pass

    fake_s=SpoofStr()
    fake_b=SpoofBytes()
    assert isinstance(fake_s,str) is True and type(fake_s) is not str
    assert isinstance(fake_b,bytes) is True and type(fake_b) is not bytes

    rejected=0
    for fn in (
        lambda:g5._canonical_beacon(fake_s),
        lambda:g5._secret_bytes_total(fake_s),
        lambda:g5._secret_bytes_total(fake_b),
        lambda:g5._canonical_beacon(RealStrSubclass("A"*16)),
        lambda:g5._secret_bytes_total(RealStrSubclass("S"*32)),
        lambda:g5._secret_bytes_total(RealBytesSubclass(b"B"*32)),
    ):
        try:
            fn()
        except g1.UnknownDomainGeneratorError:
            rejected+=1
        else:
            raise AssertionError("UNREACHABLE_TYPE_DOMAIN_WIDENING_ACCEPTED")
    assert rejected==6

    return {
        "production_beacon_domain":"EXACT_BUILTIN_STR_CONSTRUCTED_BY_FROZEN_ONE_USE_LAUNCHER",
        "production_secret_domain":"EXACT_BUILTIN_BYTES_CONSTRUCTED_BY_SECRETS_TOKEN_BYTES_32",
        "production_domain_binding":dict(PRODUCTION_DOMAIN_BINDING),
        "utf8_surrogatepass_total_on_exact_str":True,
        "hex_byte_mapping_injective":True,
        "canonical_beacon_ascii":True,
        "surrogate_codepoints_exhausted":2048,
        "isinstance_class_spoof_domain_rejected":True,
        "real_subclass_widening_rejected":True,
        "reachable_production_type_domain_total":True,
    }

def _identifier_totality()->dict[str,Any]:
    assert g5.v4 is g4
    # _ranked_labels first requires semantic keys to be unique. Sorting may
    # experience arbitrary HMAC rank collisions, and suffix tokens may collide,
    # but enumerate assigns distinct integer slots. The slot integer is part of
    # every output label, making outputs distinct regardless of all token values.
    original=g1._token
    try:
        g1._token=lambda *args,**kwargs:"COLLISION"
        for n in (1,2,3,4,12,15,27):
            keys=[f"k{i}" for i in range(n)]
            labels=g4._ranked_labels(
                b"x"*32,
                "ASCII-CANONICAL-BEACON-0000",
                scope=f"TOTALITY-{n}",
                keys=keys,
                prefix="Q-",
            )
            assert len(labels)==n
            assert len(set(labels.values()))==n
        packet=g5._generate(
            beacon="A"*16+"\ud800",
            evaluator_secret="S"*31+"\udfff",
            namespace="V6COLLIDE",
        )
        assert packet["case_count"]==27
        assert len({x["case_id"] for x in packet["visible_cases"]})==27
    finally:
        g1._token=original

    return {
        "construction":"SECRET_RANKED_STRUCTURAL_SLOT_ORDINALS_WITH_TOKEN_SUFFIX",
        "token_collision_resistance_required_for_semantic_distinctness":False,
        "all_27_case_ids_structurally_distinct":True,
        "per_case_semantic_identifier_sets_structurally_distinct":True,
        "forced_total_token_collision_survives_construction":True,
    }


def _transfer_theorem()->dict[str,Any]:
    assert g4.v2 is g2
    assert tuple(g1.PRIMITIVE_FAMILIES)==(
        "ORDER_PRESERVING_TRANSFORM",
        "PARITY_OR_SIGN_INVARIANT",
        "CONSERVATION_RELATION",
        "MONOTONE_CAUSAL_EDGE",
        "COMPOSITIONAL_REWRITE",
        "THRESHOLD_OR_PARTITION_INVARIANT",
    )
    assert g1.PRODUCTION_CASE_COUNTS[g1.TRANSFER]==12
    assert harness.MAX_TRANSFER_PROBES==2
    assert c1.MAPPING_BASIS=="STRUCTURAL_EQUIVALENCE"

    d0=Fraction(19,4)
    d1=Fraction(25,4)
    min_mag=Fraction(1,4)
    max_mag=Fraction(7,2)
    affine_gap=Fraction(3,5)*d0
    complement_gap=d0
    sat_gap=Fraction(7,10)*d0/Fraction(121,1)
    sign_shifted_min=-max_mag+d0
    step_margin=d0-Fraction(11,5)
    add2_gaps=(
        d0-(max_mag-min_mag),
        d1,
        d0,
        d1-(max_mag-min_mag),
        d0+d1,
    )
    assert affine_gap==Fraction(57,20)
    assert complement_gap==Fraction(19,4)
    assert float(sat_gap)>4.5e-9
    assert sign_shifted_min==Fraction(5,4)>0
    assert step_margin==Fraction(51,20)>0
    assert min(add2_gaps)==Fraction(3,2)

    # ADD2 indices 4 and 10 expose stable nonzero sign signatures for the two
    # real roles. Candidate V3 uses them only after support is unique, then both
    # generator and candidate evaluate the same left-to-right bias+r0+r1 Python
    # float expression.
    signatures={}
    for index in (4,10):
        r0=tuple(-1 if (j+index)%2==0 else 1 for j in range(3))
        r1=tuple(-1 if (j+index+1)%3==0 else 1 for j in range(3))
        assert r0==c3.ADD2_R0_SIG==(-1,1,-1)
        assert r1==c3.ADD2_R1_SIG==(1,-1,1)
        assert r0!=r1
        signatures[str(index)]={"r0":list(r0),"r1":list(r1)}

    return {
        "all_six_families_universal":True,
        "max_transfer_probes":2,
        "full_rediscovery_probe_floor":3,
        "affine_min_wrong_support_gap":str(affine_gap),
        "complement_min_wrong_support_gap":str(complement_gap),
        "sat_mono_min_wrong_support_gap":str(sat_gap),
        "sign_shifted_distractor_min":str(sign_shifted_min),
        "step_wrong_side_margin":str(step_margin),
        "add2_min_wrong_support_gap":str(min(add2_gaps)),
        "add2_role_signatures":signatures,
        "add2_exact_float_order_repaired":True,
        "exact_query_operation_order":"BIAS_PLUS_R0_PLUS_R1_IN_BOTH_GENERATOR_AND_CANDIDATE",
    }


def _abstention_theorem()->dict[str,Any]:
    assert tuple(g1.ABSTAIN_CLASSES)==("IDENTIFIABLE","NONIDENTIFIABLE","UNDERSPECIFIED")
    assert g1.PRODUCTION_CASE_COUNTS[g1.ABSTAIN]==15
    assert scorer.DECISIONS=={"CONCLUDE","ABSTAIN","REQUEST_DISCRIMINATOR"}
    return {
        "all_three_classes_universal":True,
        "cases_per_class":5,
        "identifier_semantics_structurally_total":True,
    }


def prove(root:Path|None=None)->dict[str,Any]:
    root=_root() if root is None else Path(root).resolve()
    bindings=_verify_bindings(root)
    string_totality=_string_totality()
    identifiers=_identifier_totality()
    transfer=_transfer_theorem()
    abstention=_abstention_theorem()
    assert g1.PRODUCTION_CASE_COUNTS=={g1.TRANSFER:12,g1.ABSTAIN:15}
    return {
        "schema":SCHEMA,
        "status":"PASS__UNIVERSAL_TOTAL_STRING_STRUCTURAL_ID_AND_EXACT_FLOAT_BOUND_EVALUATOR",
        "target_predicate":"UNKNOWN_DOMAIN_UNCOVERED_TRANSFER_AUDIT",
        "exact_subject_blobs":bindings,
        "string_interface_totality":string_totality,
        "identifier_totality_proof":identifiers,
        "transfer_proof":transfer,
        "abstention_proof":abstention,
        "scope":{
            "beacon":"FROZEN_PRODUCTION_LAUNCHER_EXACT_BUILTIN_STR__NONPRODUCTION_EXACT_BUILTIN_STR_ALSO_SUPPORTED",
            "evaluator_secret":"FROZEN_PRODUCTION_LAUNCHER_EXACT_BUILTIN_BYTES_32__NONPRODUCTION_EXACT_BUILTIN_STR_OR_BYTES_SUPPORTED",
            "population_cases":27,
            "transfer_cases":12,
            "abstention_cases":15,
            "terminal_or_production_cases_generated":0,
        },
        "theorem":(
            "FOR_EVERY_INPUT_IN_THE_EXACT_REACHABLE_FROZEN_PRODUCTION_LAUNCHER_DOMAIN__"
            "GENERATOR_V5_CANONICALIZES_BEFORE_ALL_LEGACY_RANDOMNESS__"
            "GENERATOR_V4_STRUCTURALLY_PRESERVES_SEMANTIC_IDENTIFIER_DISTINCTNESS__"
            "CANDIDATE_V3_PASSES_ALL_12_TRANSFER_AND_15_ABSTENTION_CASES_THROUGH_THE_EXACT_SCORER"
        ),
        "supersedes_failed_routes":[
            "V2_FALSE_ADD2_EXACT_FLOAT_UNIVERSAL",
            "V3_ORIGINAL_IDENTIFIER_TOTALITY_GAPS",
            "V4_TOP_LEVEL_STRING_DOMAIN_TOTALITY_CLAIM",
        ],
        "fresh_reality_required_for_this_exact_bound_evaluator_claim":False,
        "production_execution_information_gain_for_this_exact_bound_evaluator_claim":0,
        "hard_nonclaims":[
            "NO_OPEN_WORLD_UNKNOWN_DOMAIN_GENERALIZATION_BEYOND_THE_BOUND_EVALUATOR_CONTRACT",
            "NO_ACCEPTANCE_FAMILY_CAPABILITY_OR_OWNERSHIP_CREDIT_FROM_THIS_CERTIFICATE_ALONE",
            "NO_PRODUCTION_OR_TERMINAL_CASE_GENERATED_READ_OR_CONSUMED",
            "INDEPENDENT_CONTENT_BOUND_VERIFICATION_AND_SEPARATE_ROOT3_ACCEPTANCE_REDUCTION_REQUIRED",
        ],
        "accounting":{
            "incremental_spend_usd":0,
            "new_reality_units_consumed":0,
            "terminal_cases_consumed":0,
            "production_cases_generated":0,
            "acceptance_credit_delta":0,
            "family_credit_delta":0,
            "capability_credit_delta":0,
            "ownership_credit_delta":0,
        },
    }


if __name__=="__main__":
    import json
    print(json.dumps(prove(),indent=2,sort_keys=True,ensure_ascii=True))
