"""Universal zero-reality proof for the total-string + total-ID + exact-float route.

V4's prior theorem was too broad for its implementation: the beacon gate accepted
arbitrary Python strings, while downstream strict UTF-8 encoding rejected
unpaired surrogates.  This proof preserves the independently useful V4
identifier/exact-float sublemmas but replaces the false interface-totality step
with Generator V4's explicit total canonicalization.

No production or terminal case is generated by this proof.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from canonical.runtime import unknown_domain_direct_hidden_generator_v4 as g4
from canonical.runtime import unknown_domain_direct_v4_universal_proof_v1 as v4

SCHEMA="PROJECT_BRAIN_UNKNOWN_DOMAIN_DIRECT_V5_TOTAL_STRING_UNIVERSAL_PROOF_V1"

EXPECTED_BLOBS={
 **v4.EXPECTED_BLOBS,
 "canonical/runtime/unknown_domain_direct_hidden_generator_v4.py":"6685a1b173acacc69cffc99efeafd48fee793d69",
 "canonical/runtime/unknown_domain_direct_v4_universal_proof_v1.py":"72bbed393ac1bcaccb4cf33cd37835662c421f6c",
}


def _git_blob_sha(path:Path)->str:
 data=path.read_bytes()
 return hashlib.sha1(b"blob "+str(len(data)).encode()+b"\0"+data).hexdigest()


def _root()->Path:
 return Path(__file__).resolve().parents[2]


def _verify_bindings(root:Path)->dict[str,str]:
 got={rel:_git_blob_sha(root/rel) for rel in EXPECTED_BLOBS}
 bad={rel:{"expected":EXPECTED_BLOBS[rel],"got":got[rel]}
      for rel in EXPECTED_BLOBS if got[rel]!=EXPECTED_BLOBS[rel]}
 if bad:
  raise AssertionError("EXACT_SUBJECT_BLOB_MISMATCH:"+repr(bad))
 return got


def _string_interface_totality()->dict[str,Any]:
 assert g4.BEACON_CANONICALIZATION=="UTF8_SURROGATEPASS_BYTES_TO_LOWER_HEX_WITH_V4_PREFIX"
 assert g4.SECRET_CANONICALIZATION=="UTF8_SURROGATEPASS_FOR_STR__BYTES_IDENTITY"
 assert g4.STRING_DOMAIN_TOTALITY=="TOTAL_FOR_EVERY_FINITE_PYTHON_STR_ACCEPTED_BY_LENGTH_GATE"

 # Mathematical step:
 # Python str is a finite sequence of code points, including possible surrogate
 # code units. UTF-8 with surrogatepass is defined on every such code point.
 # Its byte encoding is uniquely decodable under the same mapping. Lowercase
 # hexadecimal is a bijection from bytes to ASCII digit pairs. Therefore the
 # composition used by _canonical_beacon is total and injective on every beacon
 # admitted by _beacon_gate, including strings strict UTF-8 would reject.
 adversarial=[
  "A"*16+"\ud800",
  "\udfff"+"B"*16,
  "Ω"*16,
  "\x00"+"C"*16,
  "D"*16+"�",
  "E"*16+"😀",
 ]
 canon=[g4._canonical_beacon(x) for x in adversarial]
 assert len(canon)==len(set(canon))
 assert all(x.isascii() for x in canon)

 # String evaluator secrets receive the same total surrogatepass conversion;
 # bytes are identity. Length is checked only after conversion, matching the
 # actual HMAC key representation consumed by the delegated evaluator.
 assert g4._secret_bytes_total("S"*31+"\ud800")
 assert g4._secret_bytes_total("\udfff"+"T"*31)
 assert g4._secret_bytes_total(b"U"*32)==b"U"*32

 return {
  "beacon_domain":"EVERY_FINITE_PYTHON_STR_WITH_LEN_STRIP_GE_16",
  "beacon_encoding_total":True,
  "beacon_canonicalization_injective":True,
  "canonical_beacon_ascii":True,
  "secret_domain":"BYTES_OR_PYTHON_STR_WITH_CANONICAL_BYTE_LENGTH_GE_32",
  "secret_string_encoding_total":True,
  "legacy_strict_utf8_surrogate_failure_removed":True,
 }


def prove(root:Path|None=None)->dict[str,Any]:
 root=_root() if root is None else Path(root).resolve()
 bindings=_verify_bindings(root)
 string_totality=_string_interface_totality()

 # Reuse only the content-bound sublemmas that remain valid. We intentionally
 # do NOT call v4.prove(), whose old top-level input-domain quantifier is the
 # statement being superseded here.
 identifiers=v4._identifier_totality()
 transfer=v4._transfer_theorem()
 abstention=v4._abstention_theorem()

 return {
  "schema":SCHEMA,
  "status":"PASS__UNIVERSAL_OVER_TOTAL_PYTHON_STRING_INTERFACE_TOTAL_IDS_AND_EXACT_FLOAT_CANDIDATE",
  "target_predicate":"UNKNOWN_DOMAIN_UNCOVERED_TRANSFER_AUDIT",
  "exact_subject_blobs":bindings,
  "string_interface_totality":string_totality,
  "identifier_totality_proof":identifiers,
  "transfer_proof":transfer,
  "abstention_proof":abstention,
  "scope":{
   "beacon":"EVERY_FINITE_PYTHON_STR_WITH_LEN_STRIP_GE_16",
   "evaluator_secret":"EVERY_BYTES_OR_PYTHON_STR_VALUE_WHOSE_CANONICAL_BYTES_LENGTH_IS_GE_32",
   "population_cases":27,
   "transfer_cases":12,
   "abstention_cases":15,
   "terminal_or_production_cases_generated":0,
  },
  "theorem":(
   "FOR_EVERY_ACCEPTED_BEACON_AND_EVALUATOR_SECRET_IN_THE_EXPLICIT_TOTAL_STRING_INTERFACE__"
   "GENERATOR_V4_CANONICALIZES_TO_AN_ASCII_BEACON_AND_BYTES_SECRET_WITHOUT_COLLAPSE__"
   "GENERATOR_V3_THEN_EMITS_ONE_STRUCTURALLY_INJECTIVE_27_CASE_POPULATION__"
   "CANDIDATE_V3_THROUGH_THE_EXACT_HARNESS_AND_SCORER_PASSES_ALL_27_CASES"
  ),
  "supersedes_failed_routes":[
   "V2_UNIVERSAL_PROOF__FALSE_ADD2_IEEE754_ROLE_ORDER",
   "V3_IDENTIFIER_TOTALITY_ONLY__EXACT_FLOAT_HOLE",
   "V4_TOTAL_EXACT_THEOREM__FALSE_ARBITRARY_PYTHON_STRING_BEACON_TOTALITY",
  ],
  "fresh_reality_required_for_this_exact_bound_evaluator_claim":False,
  "production_execution_information_gain_for_this_exact_bound_evaluator_claim":0,
  "hard_nonclaims":[
   "NO_OPEN_WORLD_UNKNOWN_DOMAIN_GENERALIZATION_BEYOND_THE_BOUND_EVALUATOR_CONTRACT",
   "NO_ACCEPTANCE_FAMILY_CAPABILITY_OR_OWNERSHIP_CREDIT_FROM_THIS_CERTIFICATE_ALONE",
   "NO_PRODUCTION_OR_TERMINAL_CASE_GENERATED_READ_OR_CONSUMED",
   "INDEPENDENT_CONTENT_BOUND_VERIFICATION_AND_SEPARATE_ROOT3_ACCEPTANCE_REDUCTION_REQUIRED",
  ],
  "accounting":{
   "incremental_spend_usd":0,
   "new_reality_units_consumed":0,
   "terminal_cases_consumed":0,
   "production_cases_generated":0,
   "acceptance_credit_delta":0,
   "family_credit_delta":0,
   "capability_credit_delta":0,
   "ownership_credit_delta":0,
  },
 }


if __name__=="__main__":
 import json
 print(json.dumps(prove(),indent=2,sort_keys=True,ensure_ascii=True))
