RETURN_VERIFIED_RESULT="RETURN_VERIFIED_RESULT"
ACQUIRE_MINIMUM_INFORMATION="ACQUIRE_MINIMUM_POLICY_CHANGING_INFORMATION"
ACQUIRE_AUTHORITY_BINDING="ACQUIRE_REQUIRED_AUTHORITY_BINDING"
REPAIR_ADEQUACY_COVER="REPAIR_OR_EXPAND_VERIFIABLE_ADEQUACY_COVER"
ABSTAIN_FAIL_CLOSED="ABSTAIN_FAIL_CLOSED"
def run(*args, **kwargs):
    return {"pass": False, "status": "STUB", "actual_goal_satisfaction_verified": False, "r2_meta_action": ABSTAIN_FAIL_CLOSED}
